refactor script

diff --git a/setup-script-environment b/setup-script-environment
--- a/setup-script-environment
+++ b/setup-script-environment
@@ -1,26 +1,32 @@
 #!/bin/bash
 
-if [ $# -ne 1 ]; then
-	echo "missing download URL for package"
-	exit 1
-fi
+parse_link() {
+	package_archive=`basename ${1:?}`
+	package_directory=${package_archive%%-[[:digit:]]*}
+	source_directory="${LFS:-}/sources/$package_directory"
+}
 
-package_archive=`basename ${1:?}`
-package_directory=${package_archive%%-[[:digit:]]*}
-source_directory="${LFS:-}/sources/$package_directory"
-if [ ! -d $source_directory ]; then
-	mkdir -pv $source_directory
-	echo "created directory: $source_directory"
-fi
-
-pushd $source_directory > /dev/null
-if [ ! -e $package_archive ]; then
-	wget $1
-fi
-
-decompressed_archive=${package_archive%.tar.*}
-if [ ! -d $decompressed_archive ]; then
-	tar -xf $package_archive
-fi
-
-pushd $decompressed_archive
+do_download() {
+	if [ $# -ne 1 ]; then
+		echo "missing download URL for package"
+		exit 1
+	fi
+	
+	parse_link $@
+	if [ ! -d $source_directory ]; then
+		mkdir -pv $source_directory
+		echo "created directory: $source_directory"
+	fi
+	
+	pushd $source_directory > /dev/null
+	if [ ! -e $package_archive ]; then
+		wget $1
+	fi
+	
+	decompressed_archive=${package_archive%.tar.*}
+	if [ ! -d $decompressed_archive ]; then
+		tar -xf $package_archive
+	fi
+	
+	pushd $decompressed_archive
+}
